class AppRoutes {
  AppRoutes._();
  static const initial = Splash;
  static const dashboardpage = "/Dashboard";
  static const Login = "/LoginScreen";
  static const importrelease = "/Import release order";
  static const exportrelease = "/export release order";
  static const ViewSavedAppln = "/viewsavedappln";
  static const Splash = "/SplashScreen";
  static const bgreusable = "/bg Reusable";
  static const importApplDetails = "/importApplDetails";
  static const privacy = "/privacy policy";
  static const importsaved = "/importsaved";
  static const exportsaved = "/exportsaved";
  static const exportApplnDetails = "/exportApplnDetails";
  static const importTransactionDetails = "/importTransactionDetails";
  static const exportinspection = "/ExportInspectionEntry";
  static const importinspection = "/ImportInspectionEntry";
  static const importtreatment = "/importtreatment";
  static const exporttreatment = "/exporttreatment";
  static const exportinspectionsaved = "/exportinspectionsaved";
  static const exporttreatmentsaved = "/exporttreatmentsaved";
  static const exporttreatmentSubmission = "/exporttreatmentSubmission";
  static const exportinspectionSubmission = "/exportinspectionSubmission";
  static const importinspectionsaved = "/importinspectionsaved";
  static const importtreatmentsaved = "/importtreatmentsaved";
  static const importinspectionformsubmit = "/importinspectionformsubmit";
  static const importtreatmentformsubmit = "/importtreatmentformsubmit";
  static const dutydata = "/duty";
  static const appinfo = "/appinfo";
}
